# Generated by Django 3.1 on 2020-08-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('degree', models.CharField(max_length=100, verbose_name='Education or Expertise')),
                ('short_desc', models.TextField(blank=True, null=True, verbose_name='Short Description (optional)')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday Date (optional)')),
                ('phone_number', models.IntegerField(blank=True, null=True, verbose_name='Phone Number (optional)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email (optional)')),
                ('linkedin_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='LinkedIn Link (optional)')),
                ('telegram_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telegram Link (optional)')),
                ('instagram_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram Link (optional)')),
                ('image', models.ImageField(upload_to='Avatar', verbose_name='Profile Photo')),
            ],
        ),
    ]
