# Generated by Django 3.1 on 2020-08-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_banner_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='desc',
            field=models.TextField(default='Write a description about yourself and your goals', verbose_name='About Me'),
        ),
    ]
