# Generated by Django 3.1 on 2020-08-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200814_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='desc',
            new_name='about_me',
        ),
    ]
