# Generated by Django 3.1 on 2020-08-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_myeducation_myexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myeducation',
            name='desc',
            field=models.CharField(max_length=35, verbose_name='Little Description'),
        ),
        migrations.AlterField(
            model_name='myexperience',
            name='desc',
            field=models.CharField(max_length=35, verbose_name='Little Description'),
        ),
    ]
