# Generated by Django 3.1 on 2020-08-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200814_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myeducation',
            name='desc',
            field=models.CharField(max_length=60, verbose_name='Little Description'),
        ),
        migrations.AlterField(
            model_name='myexperience',
            name='desc',
            field=models.CharField(max_length=60, verbose_name='Little Description'),
        ),
    ]
