# Generated by Django 3.1 on 2020-08-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200814_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myeducation',
            name='desc',
            field=models.CharField(max_length=100, verbose_name='Little Description'),
        ),
        migrations.AlterField(
            model_name='myexperience',
            name='desc',
            field=models.CharField(max_length=100, verbose_name='Little Description'),
        ),
    ]
