# Generated by Django 3.1 on 2020-08-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200814_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banner'},
        ),
        migrations.AlterModelOptions(
            name='contactme',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='myeducation',
            options={'verbose_name': 'My Education', 'verbose_name_plural': 'My Educations'},
        ),
        migrations.AlterModelOptions(
            name='myexperience',
            options={'verbose_name': 'My Experience', 'verbose_name_plural': 'My Experiences'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AddField(
            model_name='contactme',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Readed / Not Readed'),
        ),
    ]
