# Generated by Django 3.1 on 2020-08-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200815_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_2',
            field=models.ImageField(default='logo.png', upload_to='Avatar', verbose_name='Second Profile Photo '),
        ),
    ]
