# Generated by Django 3.1 on 2020-08-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_banner_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='myexperience',
            name='desc_2',
            field=models.TextField(blank=True, null=True, verbose_name='Description (optional)'),
        ),
    ]
