# Generated by Django 3.1 on 2020-08-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('link', models.CharField(max_length=50, verbose_name='Link')),
                ('description', models.TextField()),
                ('opinion', models.TextField(blank=True, null=True, verbose_name='My opinion about this (optional)')),
                ('file', models.FileField(upload_to='Researches')),
                ('references', models.TextField()),
            ],
            options={
                'verbose_name': 'Research',
                'verbose_name_plural': 'Researches',
            },
        ),
    ]
