# Generated by Django 3.1 on 2020-08-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_research'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='link',
            field=models.CharField(default='https://', max_length=50, verbose_name='Link'),
        ),
    ]
