# Generated by Django 3.1 on 2020-08-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200823_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='file',
            field=models.FileField(upload_to='Researches', verbose_name='Article PDF or Word'),
        ),
        migrations.AlterField(
            model_name='research',
            name='references',
            field=models.FileField(upload_to='Researches', verbose_name='References (.txt file)'),
        ),
    ]
