# Generated by Django 3.1 on 2020-08-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200823_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='opinion',
            field=models.TextField(default='Opinion', verbose_name='My opinion about this (optional)'),
        ),
    ]
