# Generated by Django 3.1 on 2020-08-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20200823_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity and Interest', 'verbose_name_plural': 'Activities and Interests'},
        ),
    ]
