# Generated by Django 3.1 on 2020-08-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20200823_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description (optional)'),
        ),
    ]
